<h4  style="
	margin: 1em 20px;
	padding: 10px;

	background-color: #f2f2f2;
	color: #555;
	font-size: 140%;
	text-align: center;
	border-top-left-radius: 5px;
	border-top-right-radius: 5px;
	border-bottom-left-radius: 5px;
	border-bottom-right-radius: 5px;
	-webkit-border-radius: 200px; ">
	SOLICITUD DE EXAMEN EXTRAORDINARIO </h4>
   <?php
    foreach ($this->data as $keyControl => $element) {
    	if ($keyControl != 'form1'){
	    	foreach ($element as $key => $value) {

	   		if ($key == 'mesa_entrada'){
	    		echo sprintf($this->translate('<b>Mesa de Entrada:</b> %s '), $value);

	     	}else if ($key == 'fecha_solicitada'){
				echo sprintf($this->translate('<b>Fecha:</b> %s <br>'), $value);

			}else if ($key == 'nombres') {
				?>
				<h5 align = "left"> DATOS DEL ALUMNO</h5><pre><?php
				echo sprintf($this->translate('<b>Nombres:</b> %s		'), $value);

			}else if ($key == 'apellidos') {
				echo sprintf($this->translate('<b>Apellidos:</b> %s		'), $value);

			}else if ($key == 'carrera') {
				echo sprintf($this->translate('<b>Carrera:</b> %s <br>'), $value);

			}else if ($key == 'telefono') {
				echo sprintf($this->translate('<b>Teléfono:</b> %s	'), $value);

			}else if ($key == 'email') {
				echo sprintf($this->translate('<b>Email:</b> %s'), $value);
				?></pre><h5 align = "left"> DATOS DE LA SOLICITUD</h5><pre><?php
			}else if ($key == 'materia') {
				echo sprintf($this->translate('<b>Asignatura:</b> %s <br>'), $value);

			}else if ($key == 'fecha_extraordinario') {
				echo sprintf($this->translate('<b>Fecha de Examen:</b> %s	'), $value);

			}else if ($key == 'motivo') {
				echo sprintf($this->translate('<b>Justificación: </b> %s	'), $value);

			}else if ($key == 'archivo') {
				echo sprintf($this->translate('<b>Documento Adjunto:</b> %s <br>'), $value);

			}


	    	}
    	}

   }
   ?></pre>
   <?php
   $this->form1->setAttribute('class', 'form-horizontal');
   $form = $this->form1;
   $form->prepare();

   echo $this->form()->openTag($form);

   ?>

   <pre>				   <?php
 //  setAttribute('class', 'btn btn-primary');


   echo sprintf(" ");
   echo $this->formRow($form->get('Anular')->setAttribute('class', 'btn btn-primary'));
   echo sprintf(" ");
   echo $this->formRow($form->get('Rechazar')->setAttribute('class', 'btn btn-primary'));
   echo sprintf(" ");
   echo $this->formRow($form->get('VistoBueno')->setAttribute('class', 'btn btn-primary'));



   echo $this->form()->closeTag();

   ?></pre>