<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Sapientia\Module'                        => __DIR__ . '/Module.php',
    'Sapientia\Controller\SapientiaController' => __DIR__ . '/src/Sapientia/Controller/SapientiaController.php',
    'SapientiaTest\Framework\TestCase'        => __DIR__ . '/tests/Sapientia/Framework/TestCase.php',
    'SapientiaTest\SampleTest'                => __DIR__ . '/tests/Sapientia/SampleTest.php',
);
