<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=itempagination
-->

<?php if ($this->pageCount): ?>
<div class="paginationControl">
<?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
 de <?php echo $this->totalItemCount; ?>

<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url($this->route, array('action' => $this->action, 'page' => $this->first, 'order_by' => $this->order_by, 'order' => $this->order)); ?>">
    Primero
  </a> |
<?php else: ?>
  <span class="disabled">Primero</span> |
<?php endif; ?>

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url($this->route, array('action' => $this->action, 'page' => $this->previous, 'order_by' => $this->order_by, 'order' => $this->order)); ?>">
    < Anterior
  </a> |
<?php else: ?>
  <span class="disabled">< Anterior</span> |
<?php endif; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url($this->route, array('action' => $this->action, 'page' => $this->next, 'order_by' => $this->order_by, 'order' => $this->order)); ?>">
    Siguiente >
  </a> |
<?php else: ?>
  <span class="disabled">Siguiente ></span> |
<?php endif; ?>

<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url($this->route, array('action' => $this->action, 'page' => $this->last, 'order_by' => $this->order_by, 'order' => $this->order)); ?>">
    Último
  </a>
<?php else: ?>
  <span class="disabled">Último</span>
<?php endif; ?>

</div>
<?php endif; ?>
