<?php echo '<?xml version="1.0" encoding="iso-8859-1"?>';?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
      "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <!-- <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" /> -->
  <title>index</title>
  <meta name="generator" content="Amaya, see http://www.w3.org/Amaya/" />
</head>

<body>

<div class="page-header">
    <h1>Situación Académica del Alumno</h1>
</div>

<p></p>
<ul>
  <li><span><a href="/solicitud/situacionacademica/calificaciones">Calificaciones</a></span></li>
  <li><span><a
    href="/solicitud/situacionacademica/asistencia">Asistencia a Clases</a></span></li>
  <li><span><a
    href="/solicitud/situacionacademica/aprobadas">Materias Aprobadas</a></span></li>
  <li><span><a href="/solicitud/situacionacademica/horario">Horario de clases</a></span></li>
  <li><span><a
    href="/solicitud/situacionacademica/materiasinscripto">Materias Inscriptas del Alumno</a></span></li>
  <li><span><a
    href="/solicitud/situacionacademica/cursadas">Materias Cursadas</a></span></li>
</ul>
</body>
</html>
