<?php
$this->headTitle($this->headTitle);
?>

<div class="page-header">
    <h1><?php echo $this->header; ?></h1>
    <h1><?php echo $this->actor; ?></h1>
</div>


<?php if (count($this->paginator)): ?>

<table class="table table-hover">
<thead>
    <tr>
		<?php foreach ($this->columnHeader as $columName): ?>		  
            <th><?= $this->translate($columName) ?></th>      	  
		<?php endforeach; ?>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
</thead>
<tbody>
<?php foreach ($this->paginator as $row => $array):
	?> <tr> 
		<?php foreach ($array as $key => $value): ?>		  
            <td><?= $this->escapehtml($value) ?></td>      	  
		<?php endforeach; ?>
		<th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
<?php
	endforeach; ?>
</tbody>
</table>
<?php endif; ?>

<br><p>&nbsp;&nbsp;</p>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'paginator/sliding',
                                    array('route' => 'solicitud/academica',
										  'action' => $this->action)
                                    );
