<?php
$this->headTitle($this->headTitle);
?>

<div class="page-header">
    <h1><?php echo $this->header; ?></h1>
</div>


<?php if (count($this->paginator)): ?>

<table class="table table-hover">
<thead>
    <tr>
        <th><?= $this->translate($this->tableFieldTitle1) ?></th>
        <th><?= $this->translate($this->tableFieldTitle2) ?></th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
</thead>
<tbody>
<?php foreach ($this->paginator as $dataItem): ?>
   <tr>
            <td><?= $this->escapehtml($dataItem[$tableField1]) ?></td>
            <td><?= $this->escapehtml($dataItem[$tableField2]) ?></td>            
            <td><?php
//                 if($this->user->getId() == $solicitud['id'] || $this->acl->isAllowed($this->user->getRole(),'actor','edit')) :
//             ?>           
            <?php
//                 endif;
//             ?>
<!--             </td> -->
            <td><?php
//                 if($this->acl->isAllowed($this->user->getRole(),'actor','delete')) :
//             ?>        
            <?php
//                 endif;
//             ?>
<!--             </td> -->
    </tr>
<?php endforeach; ?>
</tbody>
</table>
<?php endif; ?>

<br><p>&nbsp;&nbsp;</p>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'paginator/sliding',
                                    array('route' => 'solicitud/academica',
										  'action' => $this->action)
                                    );
