<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Sistema de Transacciones'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/themes/1/js-image-slider.css')
                        ->prependStylesheet($this->basePath() . '/css/style2.css')
//                         ->prependStylesheet($this->basePath() . '/generic.css')
//                         ->prependStylesheet($this->basePath() . '/css/prettyPhoto.css')
//                         ->prependStylesheet($this->basePath() . '/css/flexslider.css')
                        // ->prependStylesheet($this->basePath() . '/css/bootstrap.css')  ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js')
                                      ->prependFile($this->basePath() . '/themes/1/js-image-slider.js') 
                                      // ->prependFile($this->basePath() . '/js/jquery.js')
                                      // ->prependFile($this->basePath() . '/js/bootstrap.js')
                                      // ->prependFile($this->basePath() . '/js/docs.js')
//                                       ->prependFile($this->basePath() . '/js/setup.js')
//                                       ->prependFile($this->basePath() . '/js/jquery.easing.1.3.js')
//                                       ->prependFile($this->basePath() . '/js/all-in-one.js')
//                                       ->prependFile($this->basePath() . '/js/jquery-ui-1.8.16.custom.min.js')
//                                       ->prependFile($this->basePath() . '/js/jquery2.min.js')?>

    </head>
    <body>
		<h1>
		<br>
		<!-- Top Line -->
		</h1>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Sistema de Transacciones') ?></a>
                    <div class="nav-collapse collapse">
                    	<ul class="nav">
<?php
		$navHelper = $this->navigation('navigation');
		$containers = $navHelper->getContainer();			
		foreach($containers->getPages() as $page) {
			
			// Mostrar solo si esta permitido al usuario
			if(!$navHelper->accept($page)) {
				// accept() is used for determining if a page should be accepted when iterating containers.
				// This method checks for page visibility and verifies that the helper’s role is allowed access to the page’s resource and privilege.
				continue; /* ir a siguiente item, no permitido al rol segun ACL */
			}
            $class = "";
            if ($page->isActive()) {
                $class = "active";
            }

            if(count($page)) {
                 // if there are subpages we render the menu a bit different
                 $label  = $page->getLabel();
                 $label  = $this->translate($label); // translated label
                 $label  = $this->escapehtml($label); // sanitized label
                 printf('<li class="dropdown%s">'."\n",
                         ($class?' '.$class:'')
                 );
                 printf('    <a href="%s" class="dropdown-toggle" data-toggle="dropdown">%s<b class="caret"></b></a>'."\n",
                             $page->getHref(),
                             $label
                 );
                 echo '<ul class="dropdown-menu">'."\n";
                 foreach($page as $subPage) {
                       if(!$navHelper->accept($subPage)) {
							// Siguiente iteracion si no esta permitido al usuario
                       		continue;
                       }
                       printf("<li>%s</li>\n",$navHelper->htmlify($subPage));
                 }
                 echo "</ul></li>\n";
             }
             else {
				 echo '</ul></div><ul class="nav navbar-nav pull-right">'."\n";
          	 	 printf("<li class=\"%s\">%s</li>\n",$class,$navHelper->htmlify($page));
          	 	 echo '</ul><div class="nav-collapse collapse">	<ul class="nav">';
             }
       }
?>						</ul>
					</div><!--/.nav-collapse -->
                    <ul class="nav navbar-nav pull-right">
                        <li><a href="/user">Acceso</a></li>
                    </ul>
                </div>
            </div>
        </div>

<?php
$namespaces = array ('error','success','info','default');
foreach ($namespaces as $namespace) {
	$flashMessages = $this->flashmessenger()->render($namespace);
    if (!empty($flashMessages)) {
?>
<div id="myAlert" class="alert alert-<?= $namespace ?>" data-alert="alert">
    <a class="close" data-dismiss="alert">×</a>
    <?= $flashMessages ?>
</div>
<?php
	}
}
?>


        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2014 by Pearl Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
		<h1>
		<br>
		<!-- Bottom Line -->
		</h1>        
    </body>
</html>