<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Solicitud\Module'                        => __DIR__ . '/Module.php',
    'Solicitud\Controller\FormularioController' => __DIR__ . '/src/Solicitud/Controller/FormularioController.php',
    'SolicitudTest\Framework\TestCase'        => __DIR__ . '/tests/Solicitud/Framework/TestCase.php',
    'SolicitudTest\SampleTest'                => __DIR__ . '/tests/Solicitud/SampleTest.php',
);
