<?php
require_once('vendor/dompdf/dompdf/dompdf_config.inc.php');
$html =
'<h3>Calificaciones</h3>
Nombres: '.$nombreSol. '<br/>
Apellidos: '.$apellidoSol.' <br/>
Matricula: '.$matriculaSol.' <br/>
Carrera: '.$carreraSol.' <br/><br/><br/>
<ul><ul>
<li>Calculo I: 5</li></br>
<li>Fisica I: 5</li></br>
<li>Algebra Vectorial: 5</li></br>
<li>Introducción a la Informatica: 5</li></br>
<li>Misterio Cristiano: 5F</li></br>
<li>Calculo II: 5</li></br>
<li>Fisica II: 5</li></br>
<li>Algebra Lineal: 4</li></br>
</ul></ul>';
//echo $html;

//generacion del pdf
$dompdf = new DOMPDF();
$dompdf->load_html($html);
$dompdf->render();
$pdf = $dompdf->output();
file_put_contents("PDF/calificaciones.pdf", $pdf);
?>

<embed src = "file:///C:/Users/azo/Documents/GitHub/transacciones/PDF/calificaciones.pdf" width = 800px height = 1100px>