<?php echo '<?xml version="1.0" encoding="iso-8859-1"?>';?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
      "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <!-- <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" /> -->
  <title>index</title>
  <meta name="generator" content="Amaya, see http://www.w3.org/Amaya/" />
</head>

<body>
<h1><span>Solicitudes</span></h1>

<p></p>
<ul>
  <li><span><a href="/visualize/visualize/seccion">Solicitud de cambio de
    sección</a></span></li>
  <li><span><a
    href="/visualize/visualize/certificado">Solicitud de certificado de
    estudios</a></span></li>
  <li><span><a
    href="/visualize/visualize/colaborador">Solicitud de colaborador de
    cátedra</a></span></li>
  <li><span>Solicitud de convalidación
    de materias</span></li>
  <li><span><a
    href="/visualize/visualize/creditos">Solicitud de créditos
    académicos</a></span></li>
  <li><span><a
    href="desinscripcion">Solicitud de desinscripción de curso</a></span></li>
  <li><span><a
    href="/visualize/visualize/exoneracion">Solicitud de exoneración de
    asistencia</a></span></li>
  <li><span><a
    href="/visualize/visualize/extraordinario">Solicitud de examen
    extraordinario</a></span></li>
  <li><span>Solicitud de homologación
    de materias</span></li>
  <li><span><a
    href="/visualize/visualize/inclusion">Solicitud de inclusión de
    lista</a></span></li>
  <li><span><a
    href="/visualize/visualize/tardia">Solicitud de inscripción tardía a
    examen</a></span></li>
  <li><a
    href="/visualize/visualize/pasantia">Solicitud de pasantía</a></li>
  <li><a
    href="/visualize/visualize/reduccion">Solicitud de reducción de
    asistencia</a></li>
  <li><a href="/visualize/visualize/revisionescolaridad">Solicitud de revisión
    de escolaridad (!)</a></li>
  <li><a href="/visualize/visualize/revisionexamen">Solicitud de revisión de
    examen</a></li>
  <li><a href="/visualize/visualize/ruptura">Solicitud de ruptura de
    correlatividad</a></li>
  <li><a href="/visualize/visualize/tesis">Solicitud de tesis</a></li>
  <li><a href="/visualize/visualize/titulo">Solicitud de título</a></li>
  <li><a href="/visualize/visualize/traspaso">Solicitud de traspaso de pago de
    examen</a></li>
  <li><a href="/visualize/visualize/tutoria">Solicitud de tutoría de
  cátedra</a></li>
  <li><a href="/visualize/visualize/fuera">Solicitud para tomar materia fuera
    de la carrera</a></li>
  <li><a href="/visualize/visualize/varias">Solicitudes varias</a></li>
</ul>
</body>
</html>
