<!DOCTYPE html>
<html>
  
  <head data-gwd-animation-mode="quickMode">
    <title>Visualizar solicitudes</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="generator" content="Google Web Designer 1.0.5.0416">
    <style type="text/css">
      html, body {
        width: 100%;
        height: 100%;
        margin: 0px;
      }
      body {
        background-color: transparent;
        -webkit-transform: perspective(1400px) matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);
        -webkit-transform-style: preserve-3d;
      }
      .gwd-div-pncg {
        position: absolute;
        left: 17px;
        top: 20px;
        font-family:\'Times New Roman\';
        text-align: left;
        color: rgb(0, 0, 0);
      }
      .gwd-span-nzt4 {
        font-family: Arial;
        font-size: 25px;
      }
      .gwd-div-7d25 {
        position: absolute;
        font-family:\'Times New Roman\';
        text-align: left;
        color: rgb(0, 0, 0);
        left: 17px;
        top: 124px;
      }
      .gwd-div-fgr4 {
        position: absolute;
        font-family:\'Times New Roman\';
        text-align: left;
        color: rgb(0, 0, 0);
        left: 17px;
        top: 235px;
      }
      .gwd-div-u0te {
        position: absolute;
        left: 465px;
        top: 358px;
        font-family:\'Times New Roman\';
        text-align: left;
        color: rgb(0, 0, 0);
      }
      .gwd-div-n1bw {
        position: absolute;
        font-family:\'Times New Roman\';
        text-align: left;
        color: rgb(0, 0, 0);
        left: 465px;
        top: 358px;
      }
      .gwd-div-7361 {
        position: absolute;
        font-family:\'Times New Roman\';
        text-align: left;
        color: rgb(0, 0, 0);
        left: 701.9px;
        top: 299px;
      }
      .gwd-div-3uct {
        position: absolute;
        font-family:\'Times New Roman\';
        color: rgb(0, 0, 0);
        left: -36px;
        top: -21px;
      }
      .gwd-div-gr7d {
        -webkit-transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);
        -webkit-transform-style: preserve-3d;
        font-family:\'Times New Roman\';
      }
      .gwd-div-q5s9 {
        font-family:\'Times New Roman\';
      }
      .gwd-div-ixiw {
        font-family:\'Times New Roman\';
      }
      .gwd-div-9oyz {
        font-family:\'Times New Roman\';
      }
      .gwd-span-wh5c {
        font-family: Arial;
        font-weight: bold;
      }
      .gwd-span-psu2 {
        font-family: Arial;
        font-weight: bold;
      }
      .gwd-span-zrn0 {
        font-family: Arial;
        font-weight: bold;
      }
      .gwd-span-a62r {
        font-family: Arial;
        font-weight: bold;
      }
      .gwd-span-jcjy {
        font-family: Arial;
        font-weight: bold;
      }
      .gwd-span-qi6f {
        font-weight: bold;
        font-family: Arial;
      }
      .gwd-span-vg2h {
        font-family: Arial;
      }
      .gwd-span-iqyd {
        font-family: Arial;
      }
      .gwd-span-hfs3 {
        font-family: Arial;
      }
      .gwd-span-k312 {
        font-family: Arial;
      }
    </style>
  </head>
  
  <body>
  <div class="gwd-div-pncg">
      <br/><br/> <h3><span class="gwd-span-nzt4">Visualizar solicitudes</span></h3>
  </div>
      <a href="/visualize/visualize/extraordinario">Solicitud de extraordinario</a> <br/>
      <a href="/visualize/visualize/ruptura-correla">Solicitud de ruptura de correlatividad</a> <br/>
      <a href="/visualize/visualize/calificaciones">Calificaciones de alumno</a> <br/>
  </body>

</html>