<?php echo '<?xml version="1.0" encoding="iso-8859-1"?>';?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
      "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <title>Nuevo</title>
  <meta name="generator" content="Amaya, see http://www.w3.org/Amaya/" />
  <style type="text/css" title="Amaya theme">


/* default rules for the whole document */
body {
    font-size: 12pt;
    font-family: Times, serif;
    font-weight: normal;
    font-style: normal;
    color: black;
    background-color: white;
    line-height: 1em;
    margin-left: 4em;
    margin-right: 2em;
   }

/* paragraphs */
p  {
    padding: 0;
    margin-top: 0em;
    margin-bottom: 0em;
    text-align: justify;
    text-indent: 1em;
   }

/* headings */
h1 {
    background-color: #e8e1e1;
    font-size: 150%;
    font-weight: bold;
    font-style: normal;
    font-variant: normal;
    text-align: center;
    padding: 0;
    margin-top: .7em;
    margin-bottom: 2em;
   }
h2 {
    font-size: 130%;
    font-weight: bold;
    font-style: normal;
    padding: 0;
    margin-top: .7em;
    margin-bottom: .7em;
   }
h3 {
    font-size: 100%;
    font-weight: bold;
    font-style: normal;
    padding: 0;
    margin-top: .5em;
    margin-bottom: .5em;
   }
h4 {
    font-size: 100%;
    font-weight: bold;
    font-style: normal;
    padding: 0;
    margin-top: .3em;
    margin-bottom: .3em;
   }
h5 {
    font-size: 100%;
    font-weight: bold;
    font-style: italic;
    padding: 0;
    margin-top: .3em;
    margin-bottom: .3em;
   }
h6 {
    font-size: 100%;
    font-weight: bold;
    font-style: normal;
    padding: 0;
    margin-top: .3em;
    margin-bottom: .3em;
   }

/* divisions */
div {
    padding: 0;
    margin-top: 0em;
    margin-bottom: 0em;
   }

/* lists */
ul, ol {
    padding: 0 0 0 2em;
    margin-top: .1em;
    margin-bottom: .1em;
   }
ul ul, ol ol, ul ol, ol ul {
    margin-top: .1em;
    margin-bottom: .1em;
   }
li {
    padding: 0;
    margin-top: .1em;
    margin-bottom: .1em;
    text-align: justify;
   }
li p {
    margin-top: .1em;
    margin-bottom: .1em;
   }
dl {
    padding: 0;
    margin-top: .1em;
    margin-bottom: .1em;
    margin-left: 1em;
   }
dl dl {
    margin-top: .1em;
    margin-bottom: .1em;
   }
dt {
    padding: 0;
    font-weight: bold;
    margin-top: .1em;
    margin-bottom: .1em;
   }
dd {
    padding: 0;
    margin-top: .1em;
    margin-left: 1.5em;
    margin-bottom: .1em;
   }
dl p {
    margin-top: .1em;
    margin-bottom: .1em;
   }
th {
    background-color: #e8e1e1;
   }

/* inline */
strong {
    font-weight: bold;
   }
em {
    font-style: italic;
   }
code {
    font-family: Courier New, Courier, monospace;
   }
ins {
    background-color: inherit;
    text-decoration: underline;
   }
del {
    text-decoration: line-through;
   }

/* anchors */
a[href] {
    color: purple;
    text-decoration: underline;
   }

/* end */
  </style>
</head>

<body>
<p style="text-align:right;margin-left:auto;margin-right:0;">Mesa de Entrada N: <?php echo $mesaNro?></p>
<!-- <p style="margin-left:0;"><img src="/visualize/visualize/logo_uca" alt="logo_uca" /> </p>  -->

<h1>SOLICITUD DE PASANTIA</h1>

<p>Fecha: <?php echo $fecha?></p>

<p>Nombre y Apellidos: <?php echo ($nombre." ".$apellido)?></p>

<p><?php echo ("Matrícula: ")?><?php echo $matricula?></p>

<p>Carrera: <?php echo $carrera?></p>

<p><?php echo ("Teléfono/Celular: ")?><?php echo $telefono?></p>

<p></p>

<p></p>

<br />
<h3><?php echo ("Solicita al señor (Director Académico/Decano), el permiso para pasantía en:")?></h3>
<br />


<p></p>

<p>Lugar: <?php echo ($lugar)?></p>

<p>Dirección: <?php echo ($direccion)?></p>

<p>Email: <?php echo ($email)?></p>

<p>Motivo: <?php echo ($motivo)?></p>

<p><?php echo ("Especificación del motivo: ")?><?php echo ($esp_motivo)?></p>

<p>Documento adjunto: <?php echo ($adjunto)?></p>

<p><?php echo ("Especificación del documento adjunto: ")?><?php echo ($esp_adjunto)?></p>
<p></p>

<p></p>
<br />


<p style="text-align:left;margin-right:auto;margin-left:10em">Con todo
respeto.</p>
<br />
<br />


<p style="text-align:left;margin-left:0;margin-right:auto;"></p>

<p
style="text-align:center;margin-left:auto;margin-right:auto;">________________________</p>

<p style="text-align:center;margin-left:auto;margin-right:auto;">Firma del
alumno/a</p>
</body>
</html>
