<?php
$title = 'Lista de solicitudes';
$this->headTitle($title);
?>

<div class="page-header">
    <h1><?php echo $title; ?></h1>
</div>

<?php if (count($this->solicitudes)): ?>

<?php 
$url_order = 'DESC';  // the following lines
if ($this->order_by == 'tipo_solicitud')
	$url_order = $this->order == 'ASC' ? 'DESC' : 'ASC';
elseif ($this->order_by == 'fecha_solicitada')
	$url_order = $this->order == 'ASC' ? 'DESC' : 'ASC';
elseif ($this->order_by == 'estado_solicitud')
	$url_order = $this->order == 'ASC' ? 'DESC' : 'ASC';
elseif ($this->order_by == 'matricula')
$url_order = $this->order == 'ASC' ? 'DESC' : 'ASC';
?>



<table class="table table-hover">
<thead>
    <tr>
        <th>
        	<a href="<?= $this->url('solicitud/list', array('controller' => 'lista', 'action' => $this->listaAction, 'order_by' => 'tipo_solicitud', 'order' => $url_order), array('query' => array('filter' => $this->filter))) ?>">Tipo de solicitud<?php 
        	if ($this->order_by == 'tipo_solicitud'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?>
        	</a>
        </th>
        <th>
        	<a href="<?= $this->url('solicitud/list', array('controller' => 'lista', 'action' => $this->listaAction, 'order_by' => 'fecha_solicitada', 'order' => $url_order), array('query' => array('filter' => $this->filter))) ?>">Fecha solicitada<?php 
        	if ($this->order_by == 'fecha_solicitada'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?>
        	</a>
        </th>
        <th>
        	<a href="<?= $this->url('solicitud/list', array('controller' => 'lista', 'action' => $this->listaAction, 'order_by' => 'estado_solicitud', 'order' => $url_order), array('query' => array('filter' => $this->filter))) ?>">Estado<?php 
        	if ($this->order_by == 'estado_solicitud'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?>
        	</a>
        </th>
        <th>
            <a href="<?= $this->url('solicitud/list', array('controller' => 'lista', 'action' => $this->listaAction, 'order_by' => 'matricula', 'order' => $url_order), array('query' => array('filter' => $this->filter))) ?>">Matrícula<?php 
        	if ($this->order_by == 'matricula'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?>
        	</a>
        </th>
        <th></th>
        <th></th>
    </tr>
</thead>
<tbody>
<?php foreach ($this->solicitudes as $solicitud): ?>
   <tr>
            <td><?= $this->escapehtml($name = str_replace('_', ' ', strtoupper($solicitud['tipo_solicitud']))) ?></td>
            <td><?= $this->escapehtml($solicitud['fecha_solicitada']) ?></td>
            <td><?= $this->escapehtml($solicitud['estado_solicitud']) ?> </td>
            <td><?= $this->escapehtml($solicitud['matricula']) ?> </td>
            <td><a href="<?= $this->url('solicitud/actor', 
            		array('controller'=> 'actor', 'action'=>$this->actorAction, 'id'=> $solicitud['solicitud'])) ?>"><?= $this->translate('Visualizar') ?></a></td>
            <td><?php
//                 if($this->user->getId() == $solicitud['id'] || $this->acl->isAllowed($this->user->getRole(),'actor','edit')) :
//             ?>           
            <?php
//                 endif;
//             ?>
<!--             </td> -->
            <td><?php
//                 if($this->acl->isAllowed($this->user->getRole(),'actor','delete')) :
//             ?>
            <!-- <a href="<?= $this->url('solicitud/actor', array('controller'=> 'actor', 'action'=>'delete', 'id'=> $solicitud['solicitud'])) ?>"><?= $this->translate('Eliminar') ?></a> -->
            <?php
//                 endif;
//             ?>
<!--             </td> -->
    </tr>
<?php endforeach; ?>
</tbody>
</table>
<br><br><br>

<div class="pull-right">
<?php
	$this->form1->setAttribute('class', 'form-horizontal');
   $form = $this->form1;
   $form->prepare();

   echo $this->form()->openTag($form);
	foreach ($this->form1 as $element) {
	    if (! ($element instanceof Zend\Form\Element\Submit)) {			
	        ?> 
	            <?= $this->formElement($element)?>
	            <?= $this->formElementErrors($element)?>
		<?php
	    } else {
	        $element->setAttribute('class', 'btn btn-primary');
	    ?>
			<?=$this->formelement($element)?>
		<?php
	    }
	}

   echo $this->form()->closeTag();
?>
</div>

<?php else:
		echo 'No hay solicitudes que mostrar';
	  endif; ?>

<br><p>&nbsp;&nbsp;</p>

<?php echo $this->paginationControl($this->solicitudes,
                                    'Sliding',
                                    'paginator/sliding',
                                    array('route' => 'solicitud/list',
										  'action' => $this->listaAction,
										  'order_by' => $this->order_by, 'order' => $this->order,
										  'filter' => $this->filter)
                                    );
