
<h4  style="
	margin: 1em 20px;
	padding: 10px;

	background-color: #f2f2f2;
	color: #555;
	font-size: 140%;
	text-align: center;
	border-top-left-radius: 5px;
	border-top-right-radius: 5px;
	border-bottom-left-radius: 5px;
	border-bottom-right-radius: 5px;
	-webkit-border-radius: 200px; ">
	SOLICITUD DE CAMBIO DE SECCION </h4>
	<br> <br>
	
			 
<?php
// We call the prepare here in order to fill the initial data and adjust the form properties, if needed
//Preparamos el formulario 
$this->form1->setAttribute('class', 'form-horizontal');
$this->form1->prepare();

echo $this->form()->openTag($this->form1);
echo '<fieldset>';

// Extraemos y desplegamos cada elemento del formulario
foreach ($this->form1 as $element) {
    if (! ($element instanceof Zend\Form\Element\Submit) && ! ($element instanceof Zend\Form\Element\Button)) {

?>
<div class="control-group">
	<label class="control-label" for="<?= $element->getName() ?>"><?= $this->translate($element->getLabel()) ?></label>
	<div class="controls">
            <?= $this->formElement($element)?>
            <h5><span style="color:#E00C0C"><?= $this->formElementErrors($element)?></span></h5>
	    </div>
</div>
<?php
	
    }  else if ($element->getName() == 'enviar')  {
        $element->setAttribute('class', 'btn btn-primary'); 
        ?>
        <br>
<div class="form-actions">
<?=$this->formelement($element)?>
    
<?php
    }
    if ($element->getName() == 'cancelar'){
	$element->setAttribute('class', 'btn btn-primary');
?>
&nbsp
<?=$this->formelement($element)?>

</div>
<?php
    }
}

echo '</fieldset>';
echo $this->form()->closeTag();
?>


<script type="text/javascript">

// Carga dinamica de elementos del formulario 

$("#matricula").change(function() {
	
    $.ajax({
      url:"/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"matricula":$("#matricula").val()},
      success: function(data, textstatus, xhr){    
        	$('#carrera').html(data);
        	     
      },

	});
});

$("#carrera").change(function() {
    $.ajax({
	      url:"/solicitud/formulario/procesardatos",
	      type: "POST",
	      data:{"carrera_asignaturas_inscriptas":$("#carrera").val(), "matricula_asignaturas_inscriptas":$("#matricula").val()},
	      success: function(data, textstatus, xhr){
	        	$('#asignatura').html(data);	     
	      },
    	});
});

$("input:radio").click(function() {
	if ($('input[name=motivo]:radio:checked').val() == 'Otro'){
		
		$('#especificacion_motivo').fadeIn(1000);
	
	
	}
	if ($('input[name=motivo]:radio:checked').val() != 'Otro'){
			
		$('#especificacion_motivo').hide(100);
		
	
	}
});
$('#especificacion_motivo').hide(100);


$("input:radio").click(function() {
	if ($('input[name=tipo]:radio:checked').val() == 'Otro'){
		
		$('#descripcion').fadeIn(1000);

	}
	if ($('input[name=tipo]:radio:checked').val() != 'Otro'){
			
		$('#descripcion').hide(100);

	}
});

$('#descripcion').hide(100);


// $("#asignatura").change(function() { 
//     $.ajax({ 
// 	      url:"/solicitud/formulario/procesardatos", 
// 	      type: "POST", 
// 	      data:{"asignatura_seccion":$("#asignatura").val(), "carrera_seccion":$("#carrera").val(), "mat_seccion":$("#matricula").val()},
// 	      success: function(data, textstatus, xhr){ 
	      		
// 	        	$('#seccion').html(data);     	     
// 	      }, 
//     	} 
// 	    ); 
// }); 



</script>
