<h4  style="
	margin: 1em 20px;
	padding: 10px;

	background-color: #f2f2f2;
	color: #555;
	font-size: 140%;
	text-align: center;
	border-top-left-radius: 5px;
	border-top-right-radius: 5px;
	border-bottom-left-radius: 5px;
	border-bottom-right-radius: 5px;
	-webkit-border-radius: 200px; "> 
	 SOLICITUD DE CERTIFICADO DE ESTUDIOS </h4>
	<br> <br>
	
<?php
// We call the prepare here in order to fill the initial data and adjust the form properties, if needed
//Preparamos el formulario
$this->form1->setAttribute('class', 'form-horizontal');
$this->form1->prepare();

echo $this->form()->openTag($this->form1);
echo '<fieldset>';

// Extraemos y desplegamos cada elemento del formulario
foreach ($this->form1 as $element) {
    if (! ($element instanceof Zend\Form\Element\Submit) && ! ($element instanceof Zend\Form\Element\Button)) {

?>
<div class="control-group">
	<label class="control-label" for="<?= $element->getName() ?>"><?= $this->translate($element->getLabel()) ?></label>
	<div class="controls">
            <?= $this->formElement($element)?>
            <h5><span style="color:#E00C0C"><?= $this->formElementErrors($element)?></span></h5>
	    </div>
</div>
<?php
	
	if ( ($element->getName() == 'Email')) {
?>
	<h5 align = 'left'> DATOS ACADÉMICOS</h5>
<?php 
	echo "\n";
	}
	else if ( ($element->getName() == 'carrera_cursada')) {
?>
	<h5 align="left"> DATOS ADMINISTRATIVOS </h5>
<?php 
    } else if ( ($element->getName() == 'tipo_de_certificado')){
?>
	<h5 align="left"> SOLICITA TÍTULO DE </h5>
<?php 
	} else if ( ($element->getName() == 'tipo_de_titulo')){
?>
	<h5 align="left"> Solicité Certificados de Estudios Anteriormente</h5>
<?php 
	} else if ( ($element->getName() == 'aclaraciones')){
?>
	<h5 align="center"> Sin otro particular me despido atentamente </h5>
<?php 
	} else if ( ($element->getName() == 'matricula')){
?>
	<h5 align="left"> Certificado de estudio para la:  </h5>
<?php 
	}
    } else if ($element->getName() == 'enviar')  {
	$element->setAttribute('class', 'btn btn-primary');
	?>
        <br>
<div class="form-actions">
<?=$this->formelement($element)?>
    
<?php
    }
    if ($element->getName() == 'cancelar'){
	$element->setAttribute('class', 'btn btn-primary');
?>
&nbsp 
<?=$this->formelement($element)?>

</div>
<?php
    }
}

echo '</fieldset>';
echo $this->form()->closeTag();
?>

<script type="text/javascript">

//Carga dinamica de elementos del formulario

$("#matricula").change(function() {
	
    $.ajax({
      url:"/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"matricula":$("#matricula").val()},
      success: function(data, textstatus, xhr){
       
        	$('#carrera').html(data);
        	
        	     
      },
	});  
});

$("#carrera").change(function() {

        	$('#carrera_cursada').val($("#carrera").val());
        	       
});

	</script>
