<h4  style="
	margin: 1em 20px;
	padding: 10px;

	background-color: #f2f2f2;
	color: #555;
	font-size: 140%;
	text-align: center;
	border-top-left-radius: 5px;
	border-top-right-radius: 5px;
	border-bottom-left-radius: 5px;
	border-bottom-right-radius: 5px;
	-webkit-border-radius: 200px; "> 
	 SOLICITUD DE COLABORADOR DE CÁTEDRA </h4>
	 <br> <br>
	

<h5 align="left"> Decano <br> Facultad de Ciencias y Tecnología <br> UNIVERSIDAD CATÓLICA <br></h5>
<h5 align ="left"> De consideración <br></h5>
	 

<h5 align="left"> Se solicita que el alumno/a: <br></h5>

<?php
// We call the prepare here in order to fill the initial data and adjust the form properties, if needed
$this->form1->setAttribute('class', 'form-horizontal');
$this->form1->prepare();

echo $this->form()->openTag($this->form1);
echo '<fieldset>';

foreach ($this->form1 as $element) {
    if (! ($element instanceof Zend\Form\Element\Submit)) {
	
		if ( ($element->getName() == 'profesor')) {
			?>
		<?php
			}
        ?>
<div class="control-group">
	<label class="control-label" for="<?= $element->getName() ?>"><?= $this->translate($element->getLabel()) ?></label>
	<div class="controls">
            <?= $this->formElement($element)?>
            <?= $this->formElementErrors($element)?>
	    </div>
</div>
<?php 
 if ( ($element->getName() == 'profesor')) {
?>
		<h5 align = 'left'> quien fue propuesto
	por el Consejo de Facultad para el presente semestre lectivo.</h5>
	<h5>Las actividades que serán desarrolladas por el Alumno/a Colaborador/a de Cátedra son las <br>
son las siguientes: </h5>

<?php 
	echo "\n";
	}
	else if ( ($element->getName() == 'asignatura')) {
?>
		<h5>cuyo profesor es: </h5>
<?php 
    } else if ( ($element->getName() == 'carreras_profesor')){
?>
	<h5 align="left"> se dirige a usted con el fin de solicitar el otorgamiento de un/a <br>
	Alumno/a Colaborador/a de Cátedra. <br>
	En tal sentido, propongo a:</h5>
<?php 
	} else if ( ($element->getName() == 'carrera')){
		
?>
<h5>sea Colaborador/a de Cátedra, para el presente semestre lectivo, en la asignatura: <br></h5>

<?php 
	} else if ( ($element->getName() == 'descripcion_actividades')){
?>
	<h5 align="center"> Atentamente </h5>
<?php 
	}
    } else if ($element->getName() == 'enviar')  {
        $element->setAttribute('class', 'btn btn-primary'); 
        ?>
        <br>
<div class="form-actions">
<?=$this->formelement($element)?>
    
<?php
    }
    if ($element->getName() == 'cancelar'){
	$element->setAttribute('class', 'btn btn-primary');
?>
&nbsp 
<?=$this->formelement($element)?>

</div>	
<?php
    }
}

echo '</fieldset>';
echo $this->form()->closeTag();
?>

<script type="text/javascript">
$("#matricula").change(function() {
	
    $.ajax({
      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"matricula":$("#matricula").val()},
      success: function(data, textstatus, xhr){
     
       
        	$('#carrera').html(data);
        	     
      },

	}
    );
    
	});

	
$("#carrera").change(function() {
	    $.ajax({
		      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
		      type: "POST",
		      data:{"colaborador_asignatura":$("#carrera").val(), "mat":$("#matricula").val()},
		      success: function(data, textstatus, xhr){
		       
		        	$('#asignatura').html(data);
		        	     
		      },

			}
		    );
		
	    $('#asignatura').fadeIn(1000);
	});
	


$("#asignatura").change(function() {
	
    $.ajax({
      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"materia":$("#asignatura").val()},
      success: function(data, textstatus, xhr){

       
        	$('#profesor').html(data);
        	     
      },
      error: function(xhr, textstatus, errorThrown) {
    	 alert("AJAX call an epic failure");
   		}
	}
    );
    
	});
	

</script>