<h4 align="center"> SOLICITUD DE RUPTURA DE CORRELATIVIDAD </h4>
<?php
// We call the prepare here in order to fill the initial data and adjust the form properties, if needed
$this->form1->setAttribute('class', 'form-horizontal');
$this->form1->prepare();

echo $this->form()->openTag($this->form1);
echo '<fieldset>';

foreach ($this->form1 as $element) {
    if (! ($element instanceof Zend\Form\Element\Submit)) {
        ?>
<div class="control-group">
	<label class="control-label" for="<?= $element->getName() ?>"><?= $this->translate($element->getLabel()) ?></label>
	<div class="controls">
            <?= $this->formElement($element)?>
            <?= $this->formElementErrors($element)?>
	    </div>
</div>
<?php
	if ( ($element->getName() == 'Semestre')) {
?>
	<h4 align = 'left'> Solicito, se me permita cursar la/s asignatura/s:</h4>
<?php 
	echo "\n";
	}
	else if ( ($element->getName() == 'Semestre_asignatura')) {
?>
	<h4 align="center"> y su/s prerrequisito/s. </h4>
<?php 
    } else if ( ($element->getName() == 'Semestre_prerrequisito')){
?>
	<h4 align="center"> SIMULTÁNEAMENTE. <br> Así mismo, acepto rendir los exámenes de las asignaturas con
	prerrequisitos, una vez aprobadas las mismas, de acuerdo a la malla curricular vigente de la carrera,
	me comprometo a cumplir en todos los casos el requisito de asistencia mínima del 75% exigido <br>
	por el reglamento de la Universidad. </h4>
<?php 
	}
    } else {
        $element->setAttribute('class', 'btn btn-primary');
?>
<div class="form-actions">
<?=$this->formelement($element)?>
    </div>
<?php
    }
}

echo '</fieldset>';
echo $this->form()->closeTag();
?>