<h4  style="
	margin: 1em 20px;
	padding: 10px;

	background-color: #f2f2f2;
	color: #555;
	font-size: 140%;
	text-align: center;
	border-top-left-radius: 5px;
	border-top-right-radius: 5px;
	border-bottom-left-radius: 5px;
	border-bottom-right-radius: 5px;
	-webkit-border-radius: 200px; "> 
	 SOLICITUD DE DESINSCRIPCIÓN </h4>
	 <br> <br>

	 
<?php
// We call the prepare here in order to fill the initial data and adjust the form properties, if needed
$this->form1->setAttribute('class', 'form-horizontal');
$this->form1->prepare();

echo $this->form()->openTag($this->form1);
echo '<fieldset>';

foreach ($this->form1 as $element) {
    if (! ($element instanceof Zend\Form\Element\Submit)) {

 	
?>
<div class="control-group">
	<label class="control-label" for="<?= $element->getName() ?>"><?= $this->translate($element->getLabel()) ?></label>
	<div class="controls">
            <?= $this->formElement($element)?>
            <?= $this->formElementErrors($element)?>
	    </div>
</div>
<?php
	
	if ( ($element->getName() == 'Email')) {
?>
	<h5 align = 'left'> TIPO DE DESINSCRIPCION </h5>
<?php 
	echo "\n";
	}
	else if ( ($element->getName() == 'Resultado_requisitos')) {
?>
	<h4 align="center"> Con todo respeto. </h4>
<?php 
    }
    } else if ($element->getName() == 'enviar')  {
        $element->setAttribute('class', 'btn btn-primary'); 
        ?>
        <br>
<div class="form-actions">
<?=$this->formelement($element)?>
    
<?php
    }
    if ($element->getName() == 'cancelar'){
	$element->setAttribute('class', 'btn btn-primary');
?>
&nbsp 
<?=$this->formelement($element)?>

</div>

<?php
	}
}

echo '</fieldset>';
echo $this->form()->closeTag();
?>

<script type="text/javascript">
$("#matricula").change(function() {
	
    $.ajax({
      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"matricula":$("#matricula").val()},
      success: function(data, textstatus, xhr){
       // $('#profesor').find('option').remove().end();
       
        	$('#carrera').html(data);
        	     
      },

	}
    );
 
	});


	$("#carrera").change(function() {
	    $.ajax({
		      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
		      type: "POST",
		      data:{"carrera_asignatura":$("#carrera").val(), "mat":$("#matricula").val()},
		      success: function(data, textstatus, xhr){
		       
		        	$('#asignatura').html(data);
		        	     
		      },

			}
		    );
		
	});
	
	

	$("#asignatura").change(function() {
	    $.ajax({
		      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
		      type: "POST",
		      data:{"cod_asignatura":$("#asignatura").val()},
		      success: function(data, textstatus, xhr){
		       // $('#profesor').find('option').remove().end();
		       
		        	$('#cod_asignatura').html(data);
		        	     
		      },

			}
		    );  
  
	});


	$("input:radio").click(function() {
		//$('input[name=radioName]:checked', '#myForm').val()
 		if ($('input[name=curso_completo]:radio:checked').val() == 'Por asignatura'){
			
			//$('#especificacion_motivo').attr( 'required','required');
 		}
 		if ($('input[name=curso_completo]:radio:checked').val() != 'Por asignatura'){

			//$('#especificacion_motivo').attr( 'required',false);
 		}
	});
	

</script>