<h4  style="
	margin: 1em 20px;
	padding: 10px;

	background-color: #f2f2f2;
	color: #555;
	font-size: 140%;
	text-align: center;
	border-top-left-radius: 5px;
	border-top-right-radius: 5px;
	border-bottom-left-radius: 5px;
	border-bottom-right-radius: 5px;
	-webkit-border-radius: 200px; "> 
	 SOLICITUD DE EXONERACIÓN DE ASISTENCIA </h4>
	 <br> <br>
	 

<?php
// We call the prepare here in order to fill the initial data and adjust the form properties, if needed
$this->form1->setAttribute('class', 'form-horizontal');
$this->form1->prepare();

echo $this->form()->openTag($this->form1);
echo '<fieldset>';

foreach ($this->form1 as $element) {
    if (! ($element instanceof Zend\Form\Element\Submit)) {

?>
<div class="control-group">
	<label class="control-label" for="<?= $element->getName() ?>"><?= $this->translate($element->getLabel()) ?></label>
	<div class="controls">
            <?= $this->formElement($element)?>
            <h5><span style="color:#E00C0C"><?= $this->formElementErrors($element)?></span></h5>
	    </div>
</div>
<?php
	
	if ( ($element->getName() == 'carrera')) {
?>
	<h5> Solicito la exoneración para la asignatura:  </h5>
<?php 
	echo "\n";
	} else if ( ($element->getName() == 'asignatura') ){
?>
	<h5> La cual cursé en la sección:  </h5>
<?php 

	}else if ( ($element->getName() == 'seccion') ){
?>
	<h5> En el semestre de año:  </h5>
<?php 

	}else if ( ($element->getName() == 'semestre_anho') ){
?>
	<h5> En el año:  </h5>
<?php 

	}else if ( ($element->getName() == 'anho') ){
?>
	<br>
	<h5> Motivo de la solicitud:  </h5>
<?php 

	}
	else if ( ($element->getName() == 'especificacion_motivo')) {
?>
	
<?php 
    }
    } else if ($element->getName() == 'enviar')  {
        $element->setAttribute('class', 'btn btn-primary'); 
        ?>
        <br>
<div class="form-actions">
<?=$this->formelement($element)?>
    
<?php
    }
    if ($element->getName() == 'cancelar'){
	$element->setAttribute('class', 'btn btn-primary');
?>
&nbsp 
<?=$this->formelement($element)?>

</div>
<?php
    }
}

echo '</fieldset>';
echo $this->form()->closeTag();
?>

<script type="text/javascript">
$("#matricula").change(function() {
	
    $.ajax({
      url:"/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"matricula":$("#matricula").val()},
      success: function(data, textstatus, xhr){
      
        	$('#carrera').html(data);
        	     
      },

	}
    );

});


$("#carrera").change(function() {
	    $.ajax({
		      url:"/solicitud/formulario/procesardatos",
		      type: "POST",
		      data:{"carrera_asignaturas_cursadas":$("#carrera").val(), "matricula_asignaturas_cursadas":$("#matricula").val()},
		      success: function(data, textstatus, xhr){
		       
		        	$('#asignatura').html(data);
		        	
		        	     
		      },
		}
	);

});
	


$("#asignatura").change(function() {
    $.ajax({
	      url:"/solicitud/formulario/procesardatos",
	      type: "POST",
	      data:{"asignatura_seccion_cursada":$("#asignatura").val(), "carrera_asignaturas_cursadas":$("#carrera").val(), "matricula_asignaturas_cursadas":$("#matricula").val()},
	      success: function(data, textstatus, xhr){
	       
	        	$('#seccion').html(data);
	        	     
	      },
	}
);

});


$("#seccion").change(function() {

});


$("#semestre_anho").change(function() {

});

// $("#adjunto").click(function() {

// 	$('#tipo').fadeIn(1000);
// 	$('#descripcion').fadeIn(1000);
// });
// $('#tipo').hide();
// $('#descripcion').hide();

$("input:radio").click(function() {
		if ($('input[name=motivo]:radio:checked').val() == 'Otro'){
			
			$('#especificacion_motivo').fadeIn(1000);
		
		
		}
		if ($('input[name=motivo]:radio:checked').val() != 'Otro'){
				
			$('#especificacion_motivo').hide(100);
			
		
		}
});
	$('#especificacion_motivo').hide(100);


$("input:radio").click(function() {
		if ($('input[name=tipo]:radio:checked').val() == 'Otro'){
			
			$('#descripcion').fadeIn(1000);
		
		
		}
		if ($('input[name=tipo]:radio:checked').val() != 'Otro'){
				
			$('#descripcion').hide(100);
			
		
		}
});
	$('#descripcion').hide(100);


</script>