<h4  style="
	margin: 1em 20px;
	padding: 10px;

	background-color: #f2f2f2;
	color: #555;
	font-size: 140%;
	text-align: center;
	border-top-left-radius: 5px;
	border-top-right-radius: 5px;
	border-bottom-left-radius: 5px;
	border-bottom-right-radius: 5px;
	-webkit-border-radius: 200px; "> 
	SOLICITUD DE EXAMEN EXTRAORDINARIO </h4>
	<br> <br>

<?php

// We call the prepare here in order to fill the initial data and adjust the form properties, if needed
//Preparamos el formulario
$this->form1->setAttribute('id', 'form');
$this->form1->setAttribute('class', 'form-horizontal');
$this->form1->prepare();

echo $this->form()->openTag($this->form1);
echo '<fieldset>';

// Extraemos y desplegamos cada elemento del formulario
foreach ($this->form1 as $element) {
    if (! ($element instanceof Zend\Form\Element\Submit) && ! ($element instanceof Zend\Form\Element\Button)) {

?>
		
<div class="control-group">
	<label class="control-label" for="<?= $element->getName() ?>"><?= $this->translate($element->getLabel()) ?></label>
	<div class="controls">
            <?= $this->formElement($element)?>
            <h5><span style="color:#E00C0C"><?= $this->formElementErrors($element)?></span></h5>
	    </div>
</div>

<?php 
		
        ?>
	
<?php
	if ( ($element->getName() == 'carrera')) {
?>
	<h4 align = 'left'> Solicita al Señor Decano, examen extraordinario de la:<br></h4>
<?php 
	echo "\n";
	}
	else if ( ($element->getName() == 'profesor')) {
?>
	<h4 align="left"> <br>Motivo de la solicitud: </h4>
<?php 
    }else if ( ($element->getName() == 'descripcion')) {
?>
	<h4 align="center"> Con todo respeto. </h4>
<?php 
    }
    } else if ($element->getName() == 'enviar')  {
        $element->setAttribute('class', 'btn btn-primary'); 
        ?>
        <br>
<div class="form-actions">
<?=$this->formelement($element)?>
    
<?php
    }
    if ($element->getName() == 'cancelar'){
	$element->setAttribute('class', 'btn btn-primary');
?>
&nbsp 
<?=$this->formelement($element)?>

</div>

<?php
    }
    if ( ($element->getName() == 'Email')){
    	?>
    				
    				<?php
    		}
}


?>
<script type="text/javascript">



//Carga dinamica de elementos del formulario 

$("#matricula").change(function() {
	
    $.ajax({
      url:"/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"matricula":$("#matricula").val()},
      success: function(data, textstatus, xhr){
     
        	$('#carrera').html(data);
        	     
      },

	});
});
	

$("#carrera").change(function() {
    $.ajax({
	      url:"/solicitud/formulario/procesardatos",
	      type: "POST",
	      data:{"carrera_asignaturas_inscriptas":$("#carrera").val(), "matricula_asignaturas_inscriptas":$("#matricula").val()},
	      success: function(data, textstatus, xhr){
	        	$('#asignatura').html(data);	     
	      },
    	}
	    );
});




$("#asignatura").change(function() {
	
    $.ajax({
      url:"/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"asignatura_seccion_inscripta":$("#asignatura").val(), "carrera_asignaturas_inscriptas":$("#carrera").val(), "matricula_asignaturas_inscriptas":$("#matricula").val() },
      success: function(data, textstatus, xhr){

        	$('#seccion').html(data);
        	     
      },
      error: function(xhr, textstatus, errorThrown) {
    	 alert("AJAX call an epic failure");
   		}
	}
    );
    
});



$("#asignatura").change(function() {
	
    $.ajax({
      url:"/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"materia_profesores":$("#asignatura").val(), "seccion_profesores":$("#seccion").val(),
    	  "semestre_anho_profesores":$("#semestre_anho").val(), "anho_profesores":$("#anho").val()},
      success: function(data, textstatus, xhr){

        	$('#profesor').html(data);
        	     
      },
      error: function(xhr, textstatus, errorThrown) {
    	 alert("AJAX call an epic failure");
   		}
	}
    );
    
});


$("#seccion").change(function() {
	
    $.ajax({
      url:"/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"materia_profesores":$("#asignatura").val(), "seccion_profesores":$("#seccion").val(),
    	  "semestre_anho_profesores":$("#semestre_anho").val(), "anho_profesores":$("#anho").val()},
      success: function(data, textstatus, xhr){

        	$('#profesor').html(data);
        	     
      },
      error: function(xhr, textstatus, errorThrown) {
    	 alert("AJAX call an epic failure");
   		}
	}
    );
    
});

$("#semestre_anho").change(function() {
	
    $.ajax({
      url:"/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"materia_profesores":$("#asignatura").val(), "seccion_profesores":$("#seccion").val(),
    	  "semestre_anho_profesores":$("#semestre_anho").val(), "anho_profesores":$("#anho").val()},
      success: function(data, textstatus, xhr){

        	$('#profesor').html(data);
        	     
      },
      error: function(xhr, textstatus, errorThrown) {
    	 alert("AJAX call an epic failure");
   		}
	}
    );
    
});

$("#anho").change(function() {
	
    $.ajax({
      url:"/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"materia_profesores":$("#asignatura").val(), "seccion_profesores":$("#seccion").val(),
    	  "semestre_anho_profesores":$("#semestre_anho").val(), "anho_profesores":$("#anho").val()},
      success: function(data, textstatus, xhr){

        	$('#profesor').html(data);
        	     
      },
      error: function(xhr, textstatus, errorThrown) {
    	 alert("AJAX call an epic failure");
   		}
	}
    );
    
});
	


                           

	$("input:radio").click(function() {
		//$('input[name=radioName]:checked', '#myForm').val()
 		if ($('input[name=motivo]:radio:checked').val() == 'Otro'){

			//$('#especificacion_motivo').attr( 'required','required');
 		}
 		if ($('input[name=motivo]:radio:checked').val() != 'Otro'){

			//$('#especificacion_motivo').attr( 'required',false);
 		}
	});



	$("input:radio").click(function() {
		if ($('input[name=motivo]:radio:checked').val() == 'Otro'){
			
			$('#especificacion_motivo').fadeIn(1000);
		
		
		}
		if ($('input[name=motivo]:radio:checked').val() != 'Otro'){
				
			$('#especificacion_motivo').hide(100);
			
		
		}
});
	$('#especificacion_motivo').hide(100);


$("input:radio").click(function() {
		if ($('input[name=tipo]:radio:checked').val() == 'Otro'){
			
			$('#descripcion').fadeIn(1000);
		
		
		}
		if ($('input[name=tipo]:radio:checked').val() != 'Otro'){
				
			$('#descripcion').hide(100);
			
		
		}
});
	$('#descripcion').hide(100);

	



	
	</script>

<?php
echo '</fieldset>';
echo $this->form()->closeTag(); 
?>
