<h4  style="
	margin: 1em 20px;
	padding: 10px;

	background-color: #f2f2f2;
	color: #555;
	font-size: 140%;
	text-align: center;
	border-top-left-radius: 5px;
	border-top-right-radius: 5px;
	border-bottom-left-radius: 5px;
	border-bottom-right-radius: 5px;
	-webkit-border-radius: 200px; "> 
	SOLICITUD DE EXAMEN EXTRAORDINARIO </h4>
	<br> <br>


	
	<select id="combo1" >
    <option value="CalculoI">CalculoI</option>
    <option value="CalculoII">CalculoII</option>
</select>

<select id="combo2">
<option value="0">--Elija el Profesor por favor --</option>
</select>
<?php

// We call the prepare here in order to fill the initial data and adjust the form properties, if needed
$this->form1->setAttribute('class', 'form-horizontal');
$this->form1->prepare();

echo $this->form()->openTag($this->form1);
echo '<fieldset>';

foreach ($this->form1 as $element) {
    if (! ($element instanceof Zend\Form\Element\Submit)) {
// 			if ($element->getName() == 'profesor'){
					
// 			}
 	
?>
		
<div class="control-group">
	<label class="control-label" for="<?= $element->getName() ?>"><?= $this->translate($element->getLabel()) ?></label>
	<div class="controls">
            <?= $this->formElement($element)?>
            <?= $this->formElementErrors($element)?>
	    </div>
</div>

<?php 

		
        ?>
	
<?php
	if ( ($element->getName() == 'Email')) {
?>
	<h4 align = 'left'> Solicita al Señor Decano, examen extraordinario de la:</h4>
<?php 
	echo "\n";
	}
	else if ( ($element->getName() == 'Resultado_requisitos')) {
?>
	<h4 align="center"> Con todo respeto. </h4>
<?php 
    }
    } else if ($element->getName() == 'enviar')  {
        $element->setAttribute('class', 'btn btn-primary'); 
        ?>
        <br>
<div class="form-actions">
<?=$this->formelement($element)?>
    
<?php
    }
    if ($element->getName() == 'cancelar'){
	$element->setAttribute('class', 'btn btn-primary');
?>
&nbsp 
<?=$this->formelement($element)?>

</div>

<?php
    }
    if ( ($element->getName() == 'Email')){
    	?>
    				
    				<?php
    		}
}


?>

<script type="text/javascript">

$("#combo1").change(function() {
	
    $.ajax({
      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"materia":$("#combo1").val()},
      success: function(data, textstatus, xhr){
       // $('#profesor').find('option').remove().end();
       
        	$('#combo2').html(data);
        	     
      },
      error: function(xhr, textstatus, errorThrown) {
    	 alert("AJAX call an epic failure");
   		}
	}
    );
	});
</script>

<?php
echo '</fieldset>';
echo $this->form()->closeTag(); 
?>
