<h4 align="center"> SOLICITUD DE HOMOLOGACIÓN DE MATERIAS </h4>
<?php
// We call the prepare here in order to fill the initial data and adjust the form properties, if needed
$this->form1->setAttribute('class', 'form-horizontal');
$this->form1->prepare();

echo $this->form()->openTag($this->form1);
echo '<fieldset>';

foreach ($this->form1 as $element) {
    if (! ($element instanceof Zend\Form\Element\Submit)) {
        ?>
<div class="control-group">
	<label class="control-label" for="<?= $element->getName() ?>"><?= $this->translate($element->getLabel()) ?></label>
	<div class="controls">
            <?= $this->formElement($element)?>
            <?= $this->formElementErrors($element)?>
	    </div>
</div>
<?php
	if ( ($element->getName() == 'Email')) {
?>
	<h4 align = 'left'> Solicita al Señor Decano/Director Académico/Director de Departamento <br>
	homologación de materias: </h4>
<?php 
	echo "\n";
	}
	else if ( ($element->getName() == 'Resultado_requisitos')) {
?>
	<h4 align="center"> Con todo respeto. </h4>
<?php 
    }
    } else {
        $element->setAttribute('class', 'btn btn-primary');
        ?>
<div class="form-actions">
<?=$this->formelement($element)?>
    </div>
<?php
    }
}

echo '</fieldset>';
echo $this->form()->closeTag();
?>
