<?php if (count($this->solicitudes)): ?>

<table class="table table-hover">
<thead>
    <tr>
        <th><?= $this->translate('Carrera') ?></th>
        <th><?= $this->translate('Estado') ?></th>
        <th><?= $this->translate('Etapa') ?></th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
</thead>
<tbody>
<?php foreach ($this->solicitudes as $solicitud): ?>
   <tr>
            <td><?= $this->escapehtml($solicitud['carrera']) ?></td>
            <td><?= $this->escapehtml($solicitud['estado_solicitud']) ?></td>
            <td><?= $solicitud['etapa_actual'] ?> </td>
            <td><a href="<?= $this->url('solicitud/default', array('controller'=> 'test', 'action'=>'take', 'id'=> $solicitud['id'])) ?>"><?= $this->translate('Visualizar') ?></a></td>
            <td><?php
//                 if($this->user->getId() == $solicitud['id'] || $this->acl->isAllowed($this->user->getRole(),'test','edit')) :
//             ?>
            <a href="<?= $this->url('solicitud/default', array('controller'=> 'test', 'action'=>'edit', 'id'=> $solicitud['id'])) ?>"><?= $this->translate('Editar') ?></a>
            <?php
//                 endif;
//             ?>
<!--             </td> -->
            <td><?php
//                 if($this->acl->isAllowed($this->user->getRole(),'test','delete')) :
//             ?>
            <a href="<?= $this->url('solicitud/default', array('controller'=> 'test', 'action'=>'delete', 'id'=> $solicitud['id'])) ?>"><?= $this->translate('Eliminar') ?></a>
            <?php
//                 endif;
//             ?>
<!--             </td> -->
    </tr>
<?php endforeach; ?>
</tbody>
</table>
<?php endif; ?>

<?php echo $this->paginationControl($this->solicitudes,
                                    'Sliding',
                                    'paginator/sliding',
                                    array('route' => 'solicitud/list')
                                    );
