<h4  style="
	margin: 1em 20px;
	padding: 10px;

	background-color: #f2f2f2;
	color: #555;
	font-size: 140%;
	text-align: center;
	border-top-left-radius: 5px;
	border-top-right-radius: 5px;
	border-bottom-left-radius: 5px;
	border-bottom-right-radius: 5px;
	-webkit-border-radius: 200px; "> 
	 SOLICITUD DE ASIGNATURA FUERA DE LA MALLA CURRICULAR </h4>
	 <br> <br>

			 
<?php
// We call the prepare here in order to fill the initial data and adjust the form properties, if needed
$this->form1->setAttribute('class', 'form-horizontal');
$this->form1->prepare();

echo $this->form()->openTag($this->form1);
echo '<fieldset>';

foreach ($this->form1 as $element) {
    if (! ($element instanceof Zend\Form\Element\Submit) && ! ($element instanceof Zend\Form\Element\Button)) {

 	
?>
<div class="control-group">
	<label class="control-label" for="<?= $element->getName() ?>"><?= $this->translate($element->getLabel()) ?></label>
	<div class="controls">
            <?= $this->formElement($element)?>
            <h5><span style="color:#E00C0C"><?= $this->formElementErrors($element)?></span></h5>
	    </div>
</div>
<?php
	
	if ( ($element->getName() == 'carrera')) {
?>
	<h5 align="left">De la carrera:</h5>
<?php 
	echo "\n";
	}
	else if ( ($element->getName() == 'carrera_asignatura')) {
?>
	<h5 align="left">Solcito cursar la asignatura:</h5>
<?php 
    }else if ( ($element->getName() == 'especificacion_motivo')) {
?>
	<h5 align="center">Con todo respeto.</h5>
<?php 
    }
    } else if ($element->getName() == 'enviar')  {
        $element->setAttribute('class', 'btn btn-primary'); 
        ?>
        <br>
<div class="form-actions">
<?=$this->formelement($element)?>
    
<?php
    }
    if ($element->getName() == 'cancelar'){
	$element->setAttribute('class', 'btn btn-primary');
?>
&nbsp 
<?=$this->formelement($element)?>

</div>
<?php
    }
}

echo '</fieldset>';
echo $this->form()->closeTag();
?>

<script type="text/javascript">
$("#matricula").change(function() {
	
    $.ajax({
      url:"/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"matricula":$("#matricula").val()},
      success: function(data, textstatus, xhr){
       
        	$('#carrera').html(data);
        	     
      },

	}
    );

	});



$("#carrera_asignatura").change(function() {
    $.ajax({
	      url:"/solicitud/formulario/procesardatos",
	      type: "POST",
	      data:{"carrera_asignaturas_todas":$("#carrera_asignatura").val(), "matricula_asignaturas_todas":$("#matricula").val()},
	      success: function(data, textstatus, xhr){
	       // $('#profesor').find('option').remove().end();
	       
	        	$('#asignatura').html(data);
	        	     
	      },
		}
	    );
    

});


$("input:radio").click(function() {
	if ($('input[name=motivo]:radio:checked').val() == 'Otro'){
		
		$('#especificacion_motivo').fadeIn(1000);
	
	
	}
	if ($('input[name=motivo]:radio:checked').val() != 'Otro'){
			
		$('#especificacion_motivo').hide(100);
		
	
	}
});
$('#especificacion_motivo').hide(100);



</script>