<?php
// 		 if(isset($_POST["materia"]))
// 		 {
		    
// 		    $dbAdapter = $this->form1->sapiAdapter;
// 		    $sql = "SELECT pxc.profesor, p.nombre FROM profesores_por_curso AS pxc INNER JOIN profesores AS p ON pxc.profesor = p.profesor
// 		    			INNER JOIN cursos AS c ON pxc.curso = c.curso INNER JOIN materias AS m ON c.materia = m.materia AND m.nombre = 'CalculoII';";//.$_POST['materia'].';';
		    
// 		    $statement = $dbAdapter->query($sql);
// 		    $result    = $statement->execute();
		    
// 		    $opciones = array();
		    
// 		    foreach ($result as $res) {
// 		    	$opciones[$res['nombre']] = $res['nombre'];
// 		    }
// 		    $opciones = implode('',$opciones);
// 		    echo $opciones;
		    
// // 		    while( $fila = $result->fetch_array() )
// // 		    {
// // 		    	$opciones ='<option value="'.$fila["p.nombre"].'">'.$fila["p.nombre"].'</option>';
// // 		    }
// // 		    echo $opciones;
		    
// 		     //echo $opciones;
// 		 }
		 

// 		?>