<h4  style="
	margin: 1em 20px;
	padding: 10px;

	background-color: #f2f2f2;
	color: #555;
	font-size: 140%;
	text-align: center;
	border-top-left-radius: 5px;
	border-top-right-radius: 5px;
	border-bottom-left-radius: 5px;
	border-bottom-right-radius: 5px;
	-webkit-border-radius: 200px; "> 
	 SOLICITUD DE RUPTURA DE CORRELATIVIDAD </h4>
	 <br> <br>


<?php

// We call the prepare here in order to fill the initial data and adjust the form properties, if needed
$this->form1->setAttribute('class', 'form-horizontal');
$this->form1->prepare();

echo $this->form()->openTag($this->form1);
echo '<fieldset>';

foreach ($this->form1 as $element) {
    if (! ($element instanceof Zend\Form\Element\Submit)) {
	?>
<div class="control-group">
	<label class="control-label" for="<?= $element->getName() ?>"><?= $this->translate($element->getLabel()) ?></label>
	<div class="controls">
            <?= $this->formElement($element)?>
            <?= $this->formElementErrors($element)?>
	    </div>
</div>
<?php
		
	if ( ($element->getName() == 'Semestre')) {
?>
	<h4 align = 'left'> Solicito, se me permita cursar la/s asignatura/s:</h4>
<?php 
	echo "\n";
	}
	else if ( ($element->getName() == 'Semestre_asignatura')) {
?>
	<h4 align="center"> y su/s prerrequisito/s. </h4>
<?php 
    } else if ( ($element->getName() == 'Semestre_prerrequisito')){
?>
	<h4 align="center"> SIMULTÁNEAMENTE. <br> Así mismo, acepto rendir los exámenes de las asignaturas con
	prerrequisitos, una vez aprobadas las mismas, de acuerdo a la malla curricular vigente de la carrera,
	me comprometo a cumplir en todos los casos el requisito de asistencia mínima del 75% exigido <br>
	por el reglamento de la Universidad. </h4>
<?php 
	}
    } else if ($element->getName() == 'enviar')  {
        $element->setAttribute('class', 'btn btn-primary'); 
        ?>
        <br>
<div class="form-actions">
<?=$this->formelement($element)?>
    
<?php
    }
    if ($element->getName() == 'cancelar'){
	$element->setAttribute('class', 'btn btn-primary');
?>
&nbsp 
<?=$this->formelement($element)?>

</div>
<?php
    }
}

echo '</fieldset>';
echo $this->form()->closeTag();
?>
<script type="text/javascript">


$("#matricula").change(function() {
	
    $.ajax({
      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"matricula":$("#matricula").val()},
      success: function(data, textstatus, xhr){
       
        	$('#carrera').html(data);
        	     
      },

	}
    );
    
	});
	

$("#carrera").change(function() {
	
    $.ajax({
      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"carrera_ruptura":$("#carrera").val()},
      success: function(data, textstatus, xhr){
       
        	$('#asignatura').html(data);
        	     
      },
      error: function(xhr, textstatus, errorThrown) {
    	 alert("AJAX call an epic failure");
   		}
	}
    );

	});

	

$("#asignatura").change(function() {
	
    $.ajax({
      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"asignatura_ruptura":$("#asignatura").val()},
      success: function(data, textstatus, xhr){
   		
        	$('#prerrequisito').html(data);
        	     
      },
      error: function(xhr, textstatus, errorThrown) {
    	 alert("AJAX call an epic failure");
   		}
	}
    );
  
	});
	

$("#asignatura").change(function() {
	
    $.ajax({
      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"asignatura_semestre":$("#asignatura").val()},
      success: function(data, textstatus, xhr){
       
        	$('#semestre_asignatura').html(data);
        	     
      },
      error: function(xhr, textstatus, errorThrown) {
    	 alert("AJAX call an epic failure");
   		}
	}
    );

	});


$("#prerrequisito").change(function() {
	
    $.ajax({
      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"prerrequisito_semestre":$("#prerrequisito").val()},
      success: function(data, textstatus, xhr){
      
        	$('#semestre_prerrequisito').html(data);
        	     
      },
      error: function(xhr, textstatus, errorThrown) {
    	 alert("AJAX call an epic failure");
   		}
	}
    );

	});

</script>