<h4  style="
	margin: 1em 20px;
	padding: 10px;

	background-color: #f2f2f2;
	color: #555;
	font-size: 140%;
	text-align: center;
	border-top-left-radius: 5px;
	border-top-right-radius: 5px;
	border-bottom-left-radius: 5px;
	border-bottom-right-radius: 5px;
	-webkit-border-radius: 200px; "> 
	 SOLICITUD DE TESIS </h4>
	 <br> <br>
	 

<?php
// We call the prepare here in order to fill the initial data and adjust the form properties, if needed
$this->form1->setAttribute('class', 'form-horizontal');
$this->form1->prepare();

echo $this->form()->openTag($this->form1);
echo '<fieldset>';

foreach ($this->form1 as $element) {
    if (! ($element instanceof Zend\Form\Element\Submit) && ! ($element instanceof Zend\Form\Element\Button)) {

 	
?>
<div class="control-group">
	<label class="control-label" for="<?= $element->getName() ?>"><?= $this->translate($element->getLabel()) ?></label>
	<div class="controls">
            <?= $this->formElement($element)?>
            <h5><span style="color:#E00C0C"><?= $this->formElementErrors($element)?></span></h5>
	    </div>
</div>
<?php
	
	if ( ($element->getName() == 'carrera')) {
?>
	<h5 align="left"><br>Solicito se considere el siguiente tema de tesis: <br><br></h5>
<?php 
	echo "\n";
	}
	else if ( ($element->getName() == 'tema_tesis')) {
?>
	<h5 align="left"> Los integrantes del grupo son:  </h5>
<?php 
    }else if ( ($element->getName() == 'integrante3')) {
?>
	<h5 align="left"> Profesor tutor propuesto: </h5>
<?php 
    }else if ( ($element->getName() == 'profesor')) {
?>
	<h5 align="left"> Documentos: </h5>
<?php 
    }else if ( ($element->getName() == 'descripcion')) {
?>
	<h5 align="center"> Con todo respeto. </h5>
<?php 
    }
    } else if ($element->getName() == 'enviar')  {
        $element->setAttribute('class', 'btn btn-primary'); 
        ?>
        <br>
<div class="form-actions">
<?=$this->formelement($element)?>
    
<?php
    }
    if ($element->getName() == 'cancelar'){
	$element->setAttribute('class', 'btn btn-primary');
?>
&nbsp 
<?=$this->formelement($element)?>

</div>
<?php
    }
}

echo '</fieldset>';
echo $this->form()->closeTag();
?>

<script type="text/javascript">
$("#matricula").change(function() {
	
    $.ajax({
      url:"/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"matricula":$("#matricula").val()},
      success: function(data, textstatus, xhr){
       // $('#profesor').find('option').remove().end();
       
        	$('#carrera').html(data);
        	     
      },
//       error: function(xhr, textstatus, errorThrown) {
//     	 alert("AJAX call an epic failure");
//    		}
	}
    );

	});


$("input:radio").click(function() {
	if ($('input[name=tipo]:radio:checked').val() == 'Otro'){
		
		$('#descripcion').fadeIn(1000);
	
	
	}
	if ($('input[name=tipo]:radio:checked').val() != 'Otro'){
			
		$('#descripcion').hide(100);
		
	
	}
});
$('#descripcion').hide(100);
	
</script>