<h4  style="
	margin: 1em 20px;
	padding: 10px;

	background-color: #f2f2f2;
	color: #555;
	font-size: 140%;
	text-align: center;
	border-top-left-radius: 5px;
	border-top-right-radius: 5px;
	border-bottom-left-radius: 5px;
	border-bottom-right-radius: 5px;
	-webkit-border-radius: 200px; "> 
	 SOLICITUD DE TITULO </h4>
	 <br> <br>


<?php
// We call the prepare here in order to fill the initial data and adjust the form properties, if needed
$this->form1->setAttribute('class', 'form-horizontal');
$this->form1->prepare();

echo $this->form()->openTag($this->form1);
echo '<fieldset>';

foreach ($this->form1 as $element) {
    if (! ($element instanceof Zend\Form\Element\Submit) && ! ($element instanceof Zend\Form\Element\Button)) {
		if ( ($element->getName() == 'nombres')) {
?>

<h5 align ="left"> Presbítero Doctor <br>
MICHEL GIBAUD, Rector<br>
Universidad Católica "Nuestra Señora de la Asunción"<br>
Independencia Nacional y Comuneros <br>
Asunción - Paraguay <br> <br>
De mi consideración: <br>
El/la que suscribe  </h5>
<?php
		}
		

 	
?>
<div class="control-group">
	<label class="control-label" for="<?= $element->getName() ?>"><?= $this->translate($element->getLabel()) ?></label>
	<div class="controls">
            <?= $this->formElement($element)?>
            <h5><span style="color:#E00C0C"><?= $this->formElementErrors($element)?></span></h5>
	    </div>
</div>
<?php 
	
	if ( ($element->getName() == 'carrera')) {
?>
	<h5 align = 'left'>; adjuntando el Certificado de Estudios Legalizado, se dirige a usted <br>
	 a fin de solicitar el Título que lo habilita como:</h5>
<?php
	echo "\n";
	}
	else if ( ($element->getName() == 'nombre_titulo')) {
?>
	<h5 align="left"> Atentamente. <br> <br>
	Se adjuntan los siguientes documentos: </h5>

<?php 
	}else if ( ($element->getName() == 'fotocopia_certificado_matrimonio')) {
?>
	<h5 align="left"> Para el caso de Post-Grados: <br> 
	 </h5>

<?php 
	}else if ( ($element->getName() == 'fotocopia_simple_de_titulo')) {
?>
	<h5 align="left"> Otros Documentos Adicionales, especificar: <br> </h5>

<?php 
	}
	
	
    } else if ($element->getName() == 'enviar')  {
        $element->setAttribute('class', 'btn btn-primary'); 
        ?>
        <br>
<div class="form-actions">
<?=$this->formelement($element)?>
    
<?php
    }
    if ($element->getName() == 'cancelar'){
	$element->setAttribute('class', 'btn btn-primary');
?>
&nbsp 
<?=$this->formelement($element)?>

</div>
<?php
    }
}

echo '</fieldset>';
echo $this->form()->closeTag();
?>

<script type="text/javascript">
$("#matricula").change(function() {
	
    $.ajax({
      url:"/solicitud/formulario/procesardatos",
      type: "POST",
      data:{"matricula":$("#matricula").val()},
      success: function(data, textstatus, xhr){

        	$('#carrera').html(data);        	     
      },
	}
    );

	});


$("#carrera").change(function() {
		

		});

</script>