<h4 align="center"> SOLICITUD DE TITULO </h4>


<?php
// We call the prepare here in order to fill the initial data and adjust the form properties, if needed
$this->form1->setAttribute('class', 'form-horizontal');
$this->form1->prepare();

echo $this->form()->openTag($this->form1);
echo '<fieldset>';

foreach ($this->form1 as $element) {
    if (! ($element instanceof Zend\Form\Element\Submit)) {
        ?>
<div class="control-group">
	<label class="control-label" for="<?= $element->getName() ?>"><?= $this->translate($element->getLabel()) ?></label>
	<div class="controls">
            <?= $this->formElement($element)?>
            <?= $this->formElementErrors($element)?>
	    </div>
</div>
<?php 
	if ( ($element->getName() == 'Fecha_solicitada')) {
?>

<h5 align ="left"> Presbítero Doctor <br>
MICHEL GIBAUD, Rector<br>
Universidad Católica "Nuestra Señora de la Asunción"<br>
Independencia Nacional y Comuneros <br>
Asunción - Paraguay <br> <br>
De mi consideración: <br>
El/la que suscribe  </h5>
<?php
	}else if ( ($element->getName() == 'Email')) {
?>
	<h5 align = 'left'>; adjuntando el Certificado de Estudios Legalizado, se dirige a usted <br>
	 a fin de solicitar el Título que lo habilita como:</h5>
<?php
	echo "\n";
	}
	else if ( ($element->getName() == 'Nombre_titulo')) {
?>
	<h5 align="left"> Atentamente. <br> <br>
	Se adjuntan los siguientes documentos: </h5>

<?php 
	}
	
    } else {
        $element->setAttribute('class', 'btn btn-primary');
?>
<div class="form-actions">
<?=$this->formelement($element)?>
    </div>
<?php
    }
}

echo '</fieldset>';
echo $this->form()->closeTag();
?>