<h4  style="
	margin: 1em 20px;
	padding: 10px;

	background-color: #f2f2f2;
	color: #555;
	font-size: 140%;
	text-align: center;
	border-top-left-radius: 5px;
	border-top-right-radius: 5px;
	border-bottom-left-radius: 5px;
	border-bottom-right-radius: 5px;
	-webkit-border-radius: 200px; "> 
	 SOLICITUD DE TRASPASO DE PAGO DE EXAMEN </h4>
	 <br> <br>



<?php
// We call the prepare here in order to fill the initial data and adjust the form properties, if needed
$this->form1->setAttribute('class', 'form-horizontal');
$this->form1->prepare();

echo $this->form()->openTag($this->form1);
echo '<fieldset>';

foreach ($this->form1 as $element) {
    if (! ($element instanceof Zend\Form\Element\Submit)) {
	
?>
<div class="control-group">
	<label class="control-label" for="<?= $element->getName() ?>"><?= $this->translate($element->getLabel()) ?></label>
	<div class="controls">
            <?= $this->formElement($element)?>
            <?= $this->formElementErrors($element)?>
	    </div>
</div>
<?php
	
	//if ( ($element->getName() == 'Especificacion_motivo')) {
?>
	
<?php 
	//echo "\n";
	//}

    } else if ($element->getName() == 'enviar')  {
        $element->setAttribute('class', 'btn btn-primary'); 
        ?>
        <br>
<div class="form-actions">
<?=$this->formelement($element)?>
    
<?php
    }
    if ($element->getName() == 'cancelar'){
	$element->setAttribute('class', 'btn btn-primary');
?>
&nbsp 
<?=$this->formelement($element)?>

</div>
<?php
    }
}

echo '</fieldset>';
echo $this->form()->closeTag();
?>

<script type="text/javascript">


$("#matricula").change(function() {
	    $.ajax({
		      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
		      type: "POST",
		      data:{"matricula":$("#matricula").val()},
		      success: function(data, textstatus, xhr){
		        	$('#carrera').html(data);
	      },
		});
		
    	$('#carrera').fadeIn(1000);
	});

	$('#carrera').hide();

	
$("#carrera").change(function() {
	    $.ajax({
		      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
		      type: "POST",
		      data:{"examen_carrera":$("#carrera").val(), "matr":$("#matricula").val()},
		      success: function(data, textstatus, xhr){
		        	$('#asignatura').html(data);
		      },
			});
		
	    $('#asignatura').fadeIn(1000);
	});
	
	$('#asignatura').hide();


	
$("#asignatura").change(function() {
	    $.ajax({
		      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
		      type: "POST",
		      data:{"seccion_asignatura":$("#asignatura").val(), "matrSeccion":$("#matricula").val()},
		      success: function(data, textstatus, xhr){
		        	$('#seccion').html(data);
		      },
			});
		
	    $('#seccion').fadeIn(1000);
	});
	
	$('#seccion').hide();

	
$("#asignatura").change(function() {
	    $.ajax({
		      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
		      type: "POST",
		      data:{"opo_asignatura":$("#asignatura").val(), "matrOpo":$("#matricula").val()},
		      success: function(data, textstatus, xhr){
		        	$('#oportunidad_pagada').html(data);
		      },
			});
		
	    $('#oportunidad_pagada').fadeIn(1000);
	});
	
$('#oportunidad_pagada').hide();


$("#asignatura").change(function() {
    $.ajax({
	      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
	      type: "POST",
	      data:{"fecha_opo_asignatura":$("#asignatura").val(), "matrOpo":$("#matricula").val()},
	      success: function(data, textstatus, xhr){
	        	$('#fecha_oportunidad_pagada').html(data);
	      },
		});
	
    $('#fecha_oportunidad_pagada').fadeIn(1000);
});

$('#fecha_oportunidad_pagada').hide();

$("#asignatura").change(function() {
    $.ajax({
	      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
	      type: "POST",
	      data:{"opo_pagar_asignatura":$("#asignatura").val(), "matrOpo":$("#matricula").val()},
	      success: function(data, textstatus, xhr){
	        	$('#oportunidad_a_pagar').html(data);
	      },
		});
	
    $('#oportunidad_a_pagar').fadeIn(1000);
});

$('#oportunidad_a_pagar').hide();

$("#asignatura").change(function() {
    $.ajax({
	      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
	      type: "POST",
	      data:{"opo_pagar_asignatura":$("#asignatura").val(), "matrOpo":$("#matricula").val()},
	      success: function(data, textstatus, xhr){
	        	$('#oportunidad_a_pagar').html(data);
	      },
		});
	
    $('#oportunidad_a_pagar').fadeIn(1000);
});

$('#oportunidad_a_pagar').hide();

$("#asignatura").change(function() {
    $.ajax({
	      url:"http://transacciones.localhost/solicitud/formulario/procesardatos",
	      type: "POST",
	      data:{"fecha_opo_pagar_asignatura":$("#asignatura").val(), "matrOpo":$("#matricula").val()},
	      success: function(data, textstatus, xhr){
	        	$('#fecha_oportunidad_a_pagar').html(data);
	      },
		});
	
    $('#fecha_oportunidad_a_pagar').fadeIn(1000);
});

$('#fecha_oportunidad_a_pagar').hide();

	
</script>