<div class="page-header">
    <h1><?php echo 'Registro de Usuario' ?></h1>
</div>
 
<?php
// We call the prepare here in order to fill the initial data and adjust the form properties, if needed
$this->registerForm->setAttribute('class', 'form-horizontal');
$this->registerForm->prepare();

echo $this->form()->openTag($this->registerForm);
echo '<fieldset>';

foreach ($this->registerForm as $element) {
    if (! ($element instanceof Zend\Form\Element\Submit)) {
        ?>
<div class="control-group">
	<label class="control-label" for="<?= $element->getName() ?>"><?= $this->translate($element->getLabel()) ?></label>
	<div class="controls">
            <?= $this->formElement($element)?>
            <h5><span style="color:#E00C0C"><?= $this->formElementErrors($element)?></span></h5>
	    </div>
</div>
<?php
    } else {
        $element->setAttribute('class', 'btn btn-primary');
        ?>
<br>        
<div class="form-actions">
<?=$this->formelement($element)?>

<a href="/user" class="btn btn-primary">Cancelar</a>

    </div>
<?php
    }
}

echo '</fieldset>';
echo $this->form()->closeTag();
?>