El sistema de transacciones académicas busca facilitar el proceso de realización de solicitudes por parte de los alumnos
facilitando la elaboración y procesamiento de las solicitudes en formato electrónico. El sistema de transacciones
académicas busca entonces agilizar el proceso completo de las solicitudes de inicio a fin.
Permite a alumnos y no alumnos de la facultad de Ciencias y Tecnología elaborar sus solicitudes y ver la resolución
tomada acerca de las mismas por los funcionarios de la facultad.
