<div class="page-header">
    <h1><?php echo 'Información sobre las solicitudes' ?></h1>
</div>
<h3>Qué solicitud elegir?</h3>
<br>
<div class="row">
	<!-- INICIO PRIMERA COLUMNA -->
<div class="span4">
	<!-- SOLICITUD RUPTURA DE CORRELATIVIDAD -->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Ruptura de Correlatividad
		</div>
		<div class="toggle_container">
			Se solicita para cursar una materia sin haber pasado la materia prerequisito.
			<br>
			<b>Requisitos:</b>
			<ul class="arrow_list">
	        	<li>Haber alcanzado el 75% de asistencia en el semestre anterior.</li>
	        	<li>Promedio general superior a 3.<span style="color:red">*</span></li>
        	</ul>
        	<span style="font-size:10px; color:red">*Solo aplicable para el DICIA</span>
		</div>
	</div>
	<!-- SOLICITUD EXTRAORDINARIO -->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Extraordinario
		</div>
		<div class="toggle_container">
			Solicitud para rendir un examen en categoria de extraordinario. <br>
			<b>Requisitos:</b>
			<ul class="arrow_list">
            	<li>Estar inscripto en 3era Oportunidad.</li>
            	<li>Estar ausente en 3era Oportunidad.</li>
            	<li>Realizar la solicitud HASTA 5 días despues de la fecha de 3era Oportunidad. </li>
            </ul>
		</div>
	</div>	
	<!-- SOLICITUD DE CAMBIO DE SECCION-->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Cambio de Sección
		</div>
		<div class="toggle_container">
			Se solicita para cursar una asignatura en otra seccion habilitada. Se requiere un 
			motivo valido para la aceptacion de la solicitud.
			<br>
			<b>Motivos:</b>
			<ul class="arrow_list">
	        	<li>Solapamiento de horarios.</li>
	        	<li>Trabajo.</li>
        	</ul>
		</div>
	</div>
	<!-- SOLICITUD DE CERTIFICADIO DE ESTUDIOS -->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Certificado de Estudios
		</div>
		<div class="toggle_container">
			Solicitud para obtener tu certificado de estudios.
		</div>
	</div>
	<!-- CREDITOS-->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Créditos Académicos
		</div>
		<div class="toggle_container">
			Se solicita para obtener la cantidad de creditos que valen las actividades que 
			has realizado con el fin de recaudarlos.<br>
			<b>Requisitos:</b>
			<ul class="arrow_list">
	        	<li>Haber completado una actividad válida para la recaudacion de créditos.</li>
	        	<li>Solicitar el documento que avale la realización de dicha actividad.</li>
	        	<li>Presentar dicho documento en Recepción junto a la solicitud.</li>
        	</ul>
		</div>
	</div>
	<!-- TITULO -->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Título Universitario
		</div>
		<div class="toggle_container">
			Se utiliza para solicitar el título universitario correspondiente a la carrera.<br>
			<b>Requisitos:</b>
			<ul class="arrow_list">
	        	<li>Haber aprobado todas las asignaturas de la carrera (incluyendo tesis).</li>
	        	<li>Haber recaudado todos los creditos necesarios.</li>
	        	<li>Presentar todos los documentos pertinentes en Recepcion junto a la solicitud.</li>
        	</ul>
		</div>
	</div>
	<!-- VARIAS -->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Solicitudes Varias
		</div>
		<div class="toggle_container">
			En caso de no encontrar ninguna solicitud específica acorde a sus
			necesidades, esta es la solicitud correcta.<br>
			<b>Requisitos:</b>
			<ul class="arrow_list">
	        	<li>Detallar correctamente lo que se quiere solicitar.</li>
	        	<li>En caso de ser necesario, presentar los documentos adjuntos pertinentes.</li>
        	</ul>
		</div>
	</div>

</div>

<!-- FIN PRIMERA COLUMNA -->

<!-- INICIO SEGUNDA COLUMNA -->

<div class="span4">
	<!-- TRASPASO DE PAGO DE EXAMEN -->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Traspaso de pago de examen
		</div>
		<div class="toggle_container">
			Se solicita para traspasar el pago de una oportunidad a otra.<br>
			<b>Requisitos:</b>
			<ul class="arrow_list">
	        	<li>Solicitar 48 horas antes de la oportunidad pagada.</li>
        	</ul>
		</div>
	</div>
	<!-- REDUCCION DE ASISTENCIA -->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Reducción de Asistencia
		</div>
		<div class="toggle_container">
			Solicitud para cursar una materia y que se reduzca el requisito de porcentaje mínimo de asistencia para
			habilitar derecho a examen final. <br>
			<b>Requisitos:</b>
			<ul class="arrow_list">
            	<li>Haber alcanzado el porcentaje mínimo de asistencia el semestre anterior.</li>
            	<li>Motivos especiales:<span style="color:red">*</span>
	        		<ul class="iconic_list">
	        			<li>Trabajo</li>
	        			<li>Solapamiento de horarios</li>
	        			<li>Enfermedad</li>
	        		</ul>
	        	</li>
            </ul>
		</div>
	</div>	
	<!-- Inscripcion Tardia a EXAMEN -->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Inscripción Tardía a Examen
		</div>
		<div class="toggle_container">
			Se solicita para lograr inscribirse a una oportunidad de un examen habiendo 
			pasado la fecha tope de inscripción.<br>
			<b>Motivos posibles:</b>
			<ul class="arrow_list">
	        	<li>Enfermedad.</li>
	        	<li>Económicos.</li>
	        	<li>Accidentes.</li>
	        	<li>Otro.</li>
        	</ul>
		</div>
	</div>
	<!-- REVISION DE ESCOLARIDAD -->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Revisión de Escolaridad
		</div>
		<div class="toggle_container">
			Se pide para solicitar la asistencia de un curso específico. <br>
		</div>
	</div>	
	<!-- DESINSCRIPCION -->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Desinscripción de Curso
		</div>
		<div class="toggle_container">
			Se pide para solicitar la desinscripción de una asignatura específica o de todos los cursos inscriptos. <br>
			<b>Requisitos:</b>
			<ul class="arrow_list">
	        	<li>Presentar la solicitud antes de la fecha límite de desinscripción.
	        	<span style="color:red">*</span></li>
	        	<li>Para no pagar el monto en la siguiente cuota, la solicitud debe ser
	        		presentada hasta 10 días antes del vencimiento de la cuota.<br>
	        	<span style="font-size:10px; color:red">*Corroborar dicha fecha con la Facultad.</span></li>
        	</ul>
		</div>
	</div>	
	<!-- TESIS -->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Tesis (Exclusivo para Análisis de Sistemas)
		</div>
		<div class="toggle_container">
			Se utiliza para solicitar la aprobación para empezar a realizar la Tesis.<br>
			<b>Requisitos:</b>
			<ul class="arrow_list">
	        	<li>Haber aprobado todas las asignaturas de la carrera (incluyendo tesis).</li>
	        	<li>Tener un tema para la realización de la Tesis.</li>
        	</ul>
		</div>
	</div>
	<!-- Materia Fuera de MALLA -->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Tomar Materia Fuera de Malla Curricular
		</div>
		<div class="toggle_container">
			Se solicita tomar una materia fuera de la malla curricular de tu carrera. <br>
		</div>
	</div>	
</div>

<!-- FIN SEGUNDA COLUMNA -->

<!-- INICIO TERCERA COLUMNA -->

<div class="span4">
	<!-- EXONERACION DE ASISTENCIA -->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Exoneración de Asistencia
		</div>
		<div class="toggle_container">
			Se solicita para cursar una materia y rendir sin alcanzar un requisito de porcentaje de asistencia.
			<br>
			<b>Requisitos:</b>
			<ul class="arrow_list">
	        	<li>Haber alcanzado el 75% de asistencia en el semestre anterior.</li>
	        	<li>No haber rendido ningun final de la materia</li>
	        	<li>Motivos especiales:<span style="color:red">*</span>
	        		<ul class="iconic_list">
	        			<li>Trabajo</li>
	        			<li>Solapamiento de horarios</li>
	        		</ul>
	        	</li>
        	</ul>
        	<span style="font-size:10px; color:red">*Se debe presentar el documento adjunto específico al motivo especial.
 			</span>
		</div>
	</div>
	<!-- COLABORADOR DE CATEDRA -->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Colaborador de Cátedra
		</div>
		<div class="toggle_container">
			Solicitar ser colaborador de cátedra de una asignatura específica. <br>
			<b>Requisitos:</b>
			<ul class="arrow_list">
            	<li>Haber pasado la materia con una nota mayor o igual a 3.</li>
            	<li>Estar cursando el último año de la carrera.<span style="color:red">*</span></li>
            	<li>Contar con la aprobación del profesor de la cátedra.</li>
            </ul>
            <span style="font-size:10px; color:red">*No se aplica para el DEI o el DICIA</span>
		</div>
	</div>	
	<!-- TUTORIA DE CATEDRA -->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Tutoría de Cátedra
		</div>
		<div class="toggle_container">
			Solicitar ser tutor de la catedra de una asignatura específica. <br>
			<b>Requisitos:</b>
			<ul class="arrow_list">
            	<li>Haber pasado la materia con una nota mayor o igual a 3.</li>
            	<li>Contar con la aprobación del profesor de la cátedra.</li>
            </ul>
		</div>
	</div>	
	<!-- HOMOLOGACION -->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Homologación de Materias
		</div>
		<div class="toggle_container">
			Se solicita cuando hay un cambio de carrera y se desea convalidar las materias comunes.
			<br>
			<b>Requisitos:</b>
			<ul class="arrow_list">
	        	<li>Haber pasado las materias comunes para la homologación.</li>
        	</ul>
		</div>
	</div>
	<!-- CONVALIDACION -->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Convalidación de Materias
		</div>
		<div class="toggle_container">
			Solicítalo cuando vienes de otra facultad y quieres convalidar las materias comunes.
			<br>
			<b>Requisitos:</b>
			<ul class="arrow_list">
	        	<li>Haber pasado las materias comunes para la convalidación.</li>
	        	<li>Presentar el documento pertinente que da constancia a la aprobación de materias.</li>
        	</ul>
		</div>
	</div>
	<!-- Inclusion en Lista -->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Inclusión en Lista
		</div>
		<div class="toggle_container">
			Solicitar ser incluido en la lista luego de la emisión de la lista oficial. <br>
			<b>Motivos:</b>
			<ul class="arrow_list">
            	<li>Pago de matrícula y couta atrasados.</li>
            	<li>Retraso del trámite por alumno becado.</li>
            </ul>
		</div>
	</div>
	<!-- REVISION EXAMEN -->
	<div class="toogle_box">
		<div class="toggle closed_toggle">
			<div class="icon"></div>
			Revisión de Examen
		</div>
		<div class="toggle_container">
			Se usa para solicitar una revisión del examen final de una oportunidad rendida. <br>
			<b>Motivos Posibles:</b>
			<ul class="arrow_list">
            	<li>Disconformidad con la nota obtenida.</li>
            	<li>Confusión de apellido.</li>
            </ul>
		</div>
	</div>
</div>
</div>
<hr>
<div class="clear padding20"></div>

<!-- FIN COLUMNAS -->

<!-- DATOS IMPORTANTES DE TODAS LAS SOLICITUDES -->
<div class="row">
	<div class="span4"></div>
	<div class="span4" style="font-size:15px">
		<b>Importante:</b>
		<ul class="arrow_list" style="font-size:15px">
	    	<li>Rellenar correctamente los datos en la solicitud para enviarla.</li>
	    	<li>Luego de enviar, pasar a <b>Recepción</b> para firmar la solicitud.
	    		<span style="color:red">*</span></li>
	    	<li>En los casos que sea necesario, pasar a <b>Recepción</b> para entregar los
	    		documentos adjuntos.</li>
    	</ul>
    	<span style="font-size:15px; color:red">*Las solicitudes serán validadas recién al momento de firmarlas.</span>
	</div>
	<div class="span4"></div>
</div>
				
