<div class="page-header">
    <h1>Sistema de Transacciones Académicas</h1>
</div>
<div style="padding-top:60px;"></div>
<div class="">
    <div id="sliderFrame">
        <div id="slider">
            <img src="/images/image-slider-1.png" alt="Registro de Usuario" />
            <img src="/images/image-slider-2.png" alt="Iniciar Sesión" />
            <img src="/images/image-slider-3.png" alt="Elaboración de Solicitud" />
            <img src="/images/image-slider-4.png" alt="Lista de Solicitudes" />
            <img src="/images/image-slider-5.png" alt="Estado de la Solicitud" /> 
            <img src="/images/image-slider-6.png" alt="Resolucion de Solicitud" />       
            <img src="/images/image-slider-7.png" alt="Cerrar Sesión" />       
        </div>
    </div>
</div>
<div style="padding-top:60px;"></div>

<br>
<hr>
<div class="row">
    <div class="span4">
        <img src="/images/businesses-icon.png" alt="" class="aligncenter" />
        <p align="center">
            <em><b>Facilidad de uso</b></em><br>
            Sistema destinado a facilitar y agilizar a los usuarios el trámite de todas las solicitudes 
            que puedan realizar.
            
        </p>
    </div>

    <div class="span4">
        <img src="/images/thumb4.png" alt="" class="aligncenter" /><br>
        <p align="center">
            <em><b>Los resultados de tu solicitud al alcance de su mano</b></em><br>
            Fácil verificación del estado de tu solicitud, notificaciones por correo
            de la resolución final.
        </p>
    </div>

    <div class="span4">
        <img src="/images/Blue.png" alt="" class="aligncenter" />
        <p align="center">
            <em><b>Toda la ayuda que necesites</b></em><br>
            Proveemos de un menú de asistencia, donde el usuario puede
            verificar que solicitud es la que mejor se adapta a lo que
            en realidad quiere.
        </p>
    </div>
</div>


